import { ReactNode } from "react";
import { dir } from "i18next";
import { languages } from "../../i18n/settings";

export function generateStaticParams(): { lng: string }[] {
	return languages.map((lng) => ({ lng }));
}

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

interface RootLayoutProps {
	children: ReactNode;
	params: {
		lng: string;
	};
}

const RootLayout: React.FC<RootLayoutProps> = ({ children, params: { lng } }) => {
	return (
		<html lang={lng} dir={dir(lng)}>
			<body>{children}</body>
		</html>
	);
};

export default RootLayout;
